language: node_js
  # Node env
node_js:
  # Node version
  - 14

cache:
  yarn: true

jobs:
  include:
    - script: yarn build
      name: "Build app"
    - script: yarn test
      name: "Test app"
      script:
        - yarn cypress install
        - yarn start &
        - yarn wait-on "http-get://localhost:3000" && yarn cypress run
        - kill $(jobs -p) || true
